enso-labs/orchestra

README.md, main.py, requirements.txt, src/utils/stream.py
=> FROM feature/11-http-app-via-http-endpoint TO development

.dockerignore, .github/workflows/build.yml, .github/workflows/test.yml, Changelog.md, main.py, requirements-dev.txt, scripts/changelog.sh, scripts/db.sh, scripts/dev.sh, scripts/test.sh, src/entities/__init__.py, tests/__init__.py, tests/integration/test_main.py, tests/unit/test_example.py
=> FROM feature/17-ci-push-to-registry TO development

.github/workflows/deploy.yml, Changelog.md
=> FROM feature/19-deploy-to-dev TO development

.github/workflows/deploy.yml, Changelog.md, main.py, src/constants/__init__.py, src/routes/__init__.py, src/utils/auth.py
=> FROM feature/25-add-basic-auth TO development

.gitignore, Changelog.md, deployment/terraform/digitalocean/README.md, deployment/terraform/digitalocean/deploy.sh, deployment/terraform/digitalocean/destroy.sh, deployment/terraform/digitalocean/main.tf
This PR implements Terraform configuration for Digital Ocean deployment.
Closes #30
=> FROM feature/30-tf-do-deployment TO development

Changelog.md
=> FROM bugfix/28-cannot-auth-tools-list TO development

Changelog.md, deployment/terraform/digitalocean/deploy.sh, deployment/terraform/digitalocean/destroy.sh, deployment/terraform/digitalocean/main.tf, docker-compose.yml
This PR adds Terraform configuration for deploying the slack-agent as part of the langgraph-template project.
Closes #33
TODO:
=> FROM feature/33-deploy-app-using-terraform TO development

src/tools/__init__.py, src/tools/agent.py
=> FROM feature/38-create-agent-tool TO development

Changelog.md, src/constants/examples/__init__.py, src/entities/__init__.py, src/routes/__init__.py, src/tools/agent.py, src/utils/agent.py
This PR implements the multimodal query functionality. Closes #23
=> FROM feature/23-multimodal-query INTO development

Changelog.md, README.md, requirements.txt, src/constants/__init__.py, src/tools/__init__.py, src/tools/sql.py, src/utils/logger.py
=> FROM feature/48-sql-agent TO development

Changelog.md, backend/src/constants/examples/__init__.py, backend/src/entities/__init__.py, backend/src/flows/chatbot.py, backend/src/routes/v0/llm.py, backend/src/tools/sql.py, backend/src/utils/agent.py, backend/src/utils/llm.py, backend/src/utils/stream.py
=> FROM feature/52-ability-to-switch-llms TO development

Changelog.md, backend/src/constants/llm.py, backend/src/utils/agent.py, backend/src/utils/stream.py, docker-compose.yml, frontend/package-lock.json, frontend/package.json, frontend/src/components/ui/select.tsx, frontend/src/config/index.ts, frontend/src/entities/index.ts, frontend/src/hooks/useChatHook.ts, frontend/src/layouts/AuthLayout.tsx, frontend/src/layouts/ChatLayout.tsx, frontend/src/lib/utils/apiClient.ts, frontend/src/pages/Login.tsx, frontend/src/routes/PrivateRoute.tsx, frontend/src/routes/PublicRoute.tsx, frontend/src/services/modelService.ts
=> FROM feature/86-model-select-in-react-app TO development

frontend/src/layouts/ChatLayout.tsx, frontend/src/pages/Chat.tsx, frontend/src/styles/globals.css
=> FROM feature/91-bug-on-mobile-view TO development

Changelog.md, backend/Dockerfile, docker-compose.yml
=> FROM feature/95-fix-docker-build TO development

Changelog.md, backend/src/constants/__init__.py
=> FROM bugfix/85-static-users-failing-to-parse-json-env TO development

Changelog.md, frontend/src/components/nav/ChatNav.tsx, frontend/src/hooks/useChatHook.ts
=> FROM bugfix/104-model-select-stopped-working TO development

Changelog.md, frontend/src/components/drawers/ThreadHistoryDrawer.tsx
=> FROM bugfix/105-fix-chat-selection TO development

Changelog.md, frontend/index.html, frontend/package-lock.json, frontend/package.json, frontend/src/components/nav/ChatNav.tsx, frontend/src/components/selectors/ToolSelector.tsx, frontend/src/components/ui/badge.tsx, frontend/src/components/ui/checkbox.tsx, frontend/src/hooks/useChatHook.ts
=> FROM feature/112-can-select-tools-from-app TO development

Changelog.md, backend/src/tools/__init__.py, frontend/src/pages/Chat.tsx
=> FROM feature/115-remove-shell-local-from-demo TO development

Changelog.md, backend/requirements.txt, backend/src/constants/llm.py, frontend/src/components/drawers/ChatDrawer.tsx, frontend/src/components/nav/ChatNav.tsx, frontend/src/hooks/useChatHook.ts, frontend/src/pages/Chat.tsx
=> FROM feature/125-add-03-mini TO development

Changelog.md, backend/src/constants/__init__.py, backend/src/tools/__init__.py, backend/src/tools/shell.py, docker-compose.yml, docker/ubuntu/Dockerfile, docker/ubuntu/entrypoint.sh
=> FROM bugfix/128-fix-remote-container-exec TO development

Changelog.md, backend/src/tools/__init__.py, docker-compose.yml, docker/ubuntu/Dockerfile, frontend/src/components/cards/SystemMessageCard.tsx, frontend/src/pages/Chat.tsx
=> FROM feature/130-edit-system-message TO development

Changelog.md, backend/src/constants/__init__.py, backend/src/tools/shell.py, frontend/src/components/drawers/ThreadHistoryDrawer.tsx, frontend/src/hooks/useChatHook.ts, frontend/src/lib/utils/format.ts, frontend/src/pages/Chat.tsx
=> FROM bugfix/131-action-log-overflow TO development

Changelog.md, backend/requirements.txt, backend/src/constants/__init__.py, backend/src/constants/llm.py, backend/src/utils/llm.py, frontend/src/components/nav/ChatNav.tsx
=> FROM feature/135-google-llm-provider TO development

Changelog.md, backend/main.py, backend/migrations/versions/00000000000000_init.py, backend/src/utils/migrations.py
=> FROM bugfix/137-migrations-auto-up TO development

Changelog.md, backend/.example.env, backend/main.py, backend/migrations/versions/00000000000001_change_id_to_uuid.py, backend/migrations/versions/00000000000002_add_user_threads.py, backend/requirements.txt, backend/src/constants/__init__.py, backend/src/models/__init__.py, backend/src/routes/v0/__init__.py, backend/src/routes/v0/auth.py, backend/src/routes/v0/llm.py, backend/src/routes/v0/thread.py, backend/src/utils/agent.py, backend/src/utils/auth.py, backend/src/utils/stream.py, frontend/package-lock.json, frontend/package.json, frontend/src/components/drawers/ThreadHistoryDrawer.tsx, frontend/src/components/ui/input.tsx, frontend/src/components/ui/label.tsx, frontend/src/hooks/useChatHook.ts, frontend/src/lib/utils/apiClient.ts, frontend/src/pages/Login.tsx, frontend/src/pages/Register.tsx, frontend/src/routes/AppRoutes.tsx
=> FROM feature/139-individual-user-accounts TO development

Changelog.md, frontend/package-lock.json, frontend/package.json, frontend/src/components/cards/SystemMessageCard.tsx, frontend/src/components/inputs/ChatInput.tsx, frontend/src/components/nav/ChatNav.tsx, frontend/src/components/selectors/ToolSelector.tsx, frontend/src/components/tooltips/MainToolTip.tsx, frontend/src/components/ui/tooltip.tsx, frontend/src/pages/Chat.tsx
=> FROM feature/132-autosize-textarea TO development

Changelog.md, frontend/src/pages/Settings.tsx
=> FROM feature/145-update-settings-to-remote-dropdown TO development

Changelog.md, frontend/package-lock.json, frontend/package.json, frontend/src/components/inputs/ChatInput.tsx, frontend/src/components/inputs/ImagePreview.tsx, frontend/src/components/inputs/ImagePreviewModal.tsx, frontend/src/components/ui/dialog.tsx, frontend/src/components/ui/sonner.tsx, frontend/src/pages/Settings.tsx
=> FROM feature/145-update-settings-to-remote-dropdown TO development (part 2)

Changelog.md, backend/.example.env, backend/main.py, backend/requirements.txt, backend/src/constants/__init__.py, backend/src/routes/storage.py, backend/src/routes/v0/__init__.py, backend/src/routes/v0/storage.py, backend/src/routes/v0/thread.py, backend/src/services/storage.py, backend/src/utils/agent.py, docker-compose.yml, frontend/src/components/cards/MarkdownCard.tsx, frontend/src/components/drawers/ThreadHistoryDrawer.tsx, frontend/src/components/inputs/ChatInput.tsx, frontend/src/components/inputs/ImagePreviewModal.tsx, frontend/src/hooks/useChatHook.ts, frontend/src/hooks/useImageHook.ts
=> FROM feature/148-add-storage-endpoints TO development

frontend/src/components/inputs/ChatInput.tsx, frontend/src/hooks/useAppHook.ts
=> FROM feat/159-mobile-can-show-images TO develpment

Changelog.md, backend/main.py, backend/scripts/changelog.sh, backend/src/constants/llm.py, frontend/src/components/inputs/ChatInput.tsx, frontend/src/components/selectors/ToolSelector.tsx, frontend/src/hooks/useChatHook.ts, frontend/src/pages/Chat.tsx
=> FROM feat/153-clear-chat-inputs TO development

Changelog.md, backend/src/flows/__init__.py, backend/src/routes/v0/llm.py, backend/src/schemas/entities/__init__.py, backend/src/services/checkpoint.py, backend/src/utils/logger.py, backend/src/utils/messages.py, backend/src/utils/stream.py, frontend/index.html, frontend/src/App.tsx, frontend/src/components/drawers/ThreadHistoryDrawer.tsx, frontend/src/components/icons/XAIIcon.tsx, frontend/src/components/inputs/ChatInput.tsx, frontend/src/components/lists/ChatMessages.tsx, frontend/src/components/lists/SelectModel.tsx, frontend/src/hooks/useAppHook.ts, frontend/src/hooks/useChat.ts, frontend/src/hooks/useStream.ts, frontend/src/lib/services/threadService.ts, frontend/vite.config.ts
=> FROM bug/370-anthropic-streaming TO development

Changelog.md, frontend/src/components/drawers/ThreadHistoryDrawer.tsx, frontend/src/components/lists/SelectModel.tsx, frontend/src/hooks/useModel.tsx
=> FROM feat/372-query-params TO development
